# Generated by Django 6.0.7 on 2026-08-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(choices=[('COMMON_UNCOMMON', 'Common / Uncommon'), ('COMMON_UNCOMMON_REVERSE', 'Common / Uncommon (Reverse Holo)'), ('RARE_HOLO_REVERSE', 'Rare (Holo / Reverse)'), ('DOUBLE_RARE', 'Double Rare'), ('ULTRA_RARE', 'Ultra Rare'), ('HYPER_RARE', 'Hyper Rare'), ('ILL_RARE', 'Illustration Rare'), ('SPEC_ILL_RARE', 'Special Illustration Rare'), ('PROMO', 'Promo')], max_length=32, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(choices=[('COMMON_UNCOMMON', 'Common / Uncommon'), ('COMMON_UNCOMMON_REVERSE', 'Common / Uncommon (Reverse Holo)'), ('RARE_HOLO_REVERSE', 'Rare (Holo / Reverse)'), ('DOUBLE_RARE', 'Double Rare'), ('ULTRA_RARE', 'Ultra Rare'), ('HYPER_RARE', 'Hyper Rare'), ('ILL_RARE', 'Illustration Rare'), ('SPEC_ILL_RARE', 'Special Illustration Rare'), ('PROMO', 'Promo')], max_length=32)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('set_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Card entries',
            },
        ),
    ]
