# Generated by Django 6.0.7 on 2026-08-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_bulk_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkcount',
            name='rarity',
            field=models.CharField(choices=[('COMMON_UNCOMMON', 'Common / Uncommon'), ('COMMON_UNCOMMON_REVERSE', 'Common / Uncommon (Reverse Holo)'), ('RARE_HOLO', 'Rare (Holo)'), ('RARE_REVERSE', 'Rare (Reverse Holo)'), ('DOUBLE_RARE', 'Double Rare'), ('ULTRA_RARE', 'Ultra Rare'), ('HYPER_RARE', 'Hyper Rare'), ('ILL_RARE', 'Illustration Rare'), ('SPEC_ILL_RARE', 'Special Illustration Rare'), ('PROMO', 'Promo')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='cardentry',
            name='rarity',
            field=models.CharField(choices=[('COMMON_UNCOMMON', 'Common / Uncommon'), ('COMMON_UNCOMMON_REVERSE', 'Common / Uncommon (Reverse Holo)'), ('RARE_HOLO', 'Rare (Holo)'), ('RARE_REVERSE', 'Rare (Reverse Holo)'), ('DOUBLE_RARE', 'Double Rare'), ('ULTRA_RARE', 'Ultra Rare'), ('HYPER_RARE', 'Hyper Rare'), ('ILL_RARE', 'Illustration Rare'), ('SPEC_ILL_RARE', 'Special Illustration Rare'), ('PROMO', 'Promo')], max_length=32),
        ),
    ]
