# Generated by Django 6.1 on 2026-08-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_split_rare_bulk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkcount',
            name='rarity',
            field=models.CharField(choices=[('COMMON_UNCOMMON', 'Common / Uncommon'), ('COMMON_UNCOMMON_REVERSE', 'Common / Uncommon (Reverse Holo)'), ('RARE_HOLO', 'Rare (Holo)'), ('RARE_REVERSE', 'Rare (Reverse Holo)'), ('DOUBLE_RARE', 'Double Rare'), ('ULTRA_RARE', 'Ultra Rare'), ('HYPER_RARE', 'Hyper Rare'), ('MEGA_HYPER_RARE', 'Mega Hyper Rare'), ('ILL_RARE', 'Illustration Rare'), ('SPEC_ILL_RARE', 'Special Illustration Rare'), ('ACE_SPEC_RARE', 'ACE SPEC Rare'), ('SHINY_RARE', 'Shiny Rare'), ('SHINY_ULTRA_RARE', 'Shiny Ultra Rare'), ('SECRET_RARE', 'Secret Rare'), ('PROMO', 'Promo')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='cardentry',
            name='rarity',
            field=models.CharField(choices=[('COMMON_UNCOMMON', 'Common / Uncommon'), ('COMMON_UNCOMMON_REVERSE', 'Common / Uncommon (Reverse Holo)'), ('RARE_HOLO', 'Rare (Holo)'), ('RARE_REVERSE', 'Rare (Reverse Holo)'), ('DOUBLE_RARE', 'Double Rare'), ('ULTRA_RARE', 'Ultra Rare'), ('HYPER_RARE', 'Hyper Rare'), ('MEGA_HYPER_RARE', 'Mega Hyper Rare'), ('ILL_RARE', 'Illustration Rare'), ('SPEC_ILL_RARE', 'Special Illustration Rare'), ('ACE_SPEC_RARE', 'ACE SPEC Rare'), ('SHINY_RARE', 'Shiny Rare'), ('SHINY_ULTRA_RARE', 'Shiny Ultra Rare'), ('SECRET_RARE', 'Secret Rare'), ('PROMO', 'Promo')], max_length=32),
        ),
    ]
