# Generated by Django 6.1 on 2026-08-20 09:18

from django.db import migrations

SET_DATA = [
    ("Mega Evolution", "MEG"),
    ("Pitch Black", "PBL"),
    ("Chaos Rising", "CRI"),
    ("Perfect Order", "POR"),
    ("Ascended Heroes", "ASC"),
    ("Phantasmal Flames", "PFL"),
    ("Mega Evolution Energy", "MEE"),
    ("Mega Evolution Promos", "MEP"),
    ("White Flare", "WHT"),
    ("Scarlet & Violet Energy", "SVE"),
    ("Black Bolt", "BLK"),
    ("Destined Rivals", "DRI"),
    ("Journey Together", "JTG"),
    ("Prismatic Evolutions", "PRE"),
    ("Surging Sparks", "SSP"),
    ("Stellar Crown", "SCR"),
    ("Shrouded Fable", "SFA"),
    ("Twilight Masquerade", "TWM"),
    ("Temporal Forces", "TEF"),
    ("Paldean Fates", "PAF"),
    ("Paradox Rift", "PAR"),
    ("151", "MEW"),
    ("Obsidian Flames", "OBF"),
    ("Paldea Evolved", "PAL"),
    ("Scarlet & Violet", "SVI"),
    ("Scarlet & Violet Promos", "SVP"),
]


def migrate_set_names(apps, schema_editor):
    Set = apps.get_model("inventory", "Set")
    CardEntry = apps.get_model("inventory", "CardEntry")

    code_to_set = {}
    for name, code in SET_DATA:
        set_obj, _ = Set.objects.get_or_create(name=name, defaults={"code": code})
        code_to_set[code] = set_obj

    # linking existing CardEntry rows by matching their old set_name (a code) to the new Set
    for card in CardEntry.objects.all():
        old_code = (card.set_name or "").strip()
        if old_code in code_to_set:
            card.set = code_to_set[old_code]
            card.save()


def reverse_migrate_set_names(apps, schema_editor):
    CardEntry = apps.get_model("inventory", "CardEntry")
    CardEntry.objects.update(set=None)
    # intentionally not deleting Set rows on reverse, to avoid destroying data if this migration is rolled back after further edits.


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_set_cardentry_set"),
    ]

    operations = [
        migrations.RunPython(migrate_set_names, reverse_migrate_set_names),
    ]
