# Generated by Django 6.1 on 2026-08-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_migrate_set_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardentry',
            name='set_name',
        ),
    ]
