# Generated by Django 6.1 on 2026-08-29 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_cardentry_set_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('card_number', models.CharField(blank=True, max_length=20)),
                ('rarity', models.CharField(blank=True, choices=[('COMMON_UNCOMMON', 'Common / Uncommon'), ('COMMON_UNCOMMON_REVERSE', 'Common / Uncommon (Reverse Holo)'), ('RARE_HOLO', 'Rare (Holo)'), ('RARE_REVERSE', 'Rare (Reverse Holo)'), ('DOUBLE_RARE', 'Double Rare'), ('ULTRA_RARE', 'Ultra Rare'), ('HYPER_RARE', 'Hyper Rare'), ('MEGA_HYPER_RARE', 'Mega Hyper Rare'), ('ILL_RARE', 'Illustration Rare'), ('SPEC_ILL_RARE', 'Special Illustration Rare'), ('ACE_SPEC_RARE', 'ACE SPEC Rare'), ('SHINY_RARE', 'Shiny Rare'), ('SHINY_ULTRA_RARE', 'Shiny Ultra Rare'), ('SECRET_RARE', 'Secret Rare'), ('PROMO', 'Promo')], max_length=32)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_cards', to='inventory.set')),
            ],
            options={
                'ordering': ['set', 'card_number'],
                'unique_together': {('name', 'set', 'card_number')},
            },
        ),
    ]
