# Generated by Django 6.1 on 2026-09-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_knowncard'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='generation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
