# Generated by Django 6.1 on 2026-09-28 10:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_backfill_set_generations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('BOOSTER_PACK', 'Booster Pack'), ('ETB', 'Elite Trainer Box (ETB)'), ('BOOSTER_BUNDLE', 'Booster Bundle (6 packs)'), ('MINI_TIN', 'Mini Tin (2 packs)'), ('POKE_BALL_TIN', 'Poké Ball Tin (3 packs)'), ('TIN', 'Regular Tin (4-5 packs)'), ('COLLECTION_BOX', 'Collection Box'), ('BOOSTER_BOX', 'Booster Box (36 packs)'), ('PREBUILT_DECK', 'Prebuilt Deck'), ('BUILD_BATTLE', 'Build & Battle'), ('UPC', 'Ultra Premium Collection (UPC)'), ('TOURNAMENT', 'Tournament Collection'), ('CHEST', "Collector's Chest / Lunchbox"), ('TOOLKIT', "Trainer's Toolkit"), ('MISC', 'Misc')], max_length=32)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('returns', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.set')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
